controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
twitch_status:
    path: /twitchStatus
    controller: App\Controller\TwitchController::checkStreamerStatus
